---
- set_fact:
    garbd_service: garbd
  when: os == 'ubuntu'
- set_fact:
    garbd_service: garb
  when: os == 'rhel'


- name: create mysql user
  user:
    name: mysql
    comment: mysql service user
    shell: /bin/false
    system: yes
    home: /var/lib/mysql

- name: install python-pycurl
  package:
    name: python-pycurl
  register: result
  until: result|succeeded
  retries: 5
