---
dependencies:
  - role: nova-common
  - role: openstack-database
    database_name: nova
  - role: openstack-database
    database_name: nova_api
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
  - role: openstack-firewall
    rule_name: nova
    rules_type_input:
      - { protocol: tcp, port: "{{ endpoints.nova.port.haproxy_api }}" }
      - { protocol: tcp, port: "{{ endpoints.novnc.port.haproxy_api }}" }
