---
inspec:
  version: ~
  enabled: true
  interval: 3600
  dependency_install_method: 'tar'
  dependency_path: /etc/inspec/
  profile_dependencies:
    - name: inspec-openstack-security
      version: master
      url: https://github.com/chef-partners/inspec-openstack-security/archive/master.tar.gz
    - name: inspec-stig-rhel7
      version: master
      url: https://github.com/inspec-stigs/inspec-stig-rhel7/archive/master.tar.gz
  openstack:
    horizon:
      required_controls:
        - check-dashboard-01
        - check-dashboard-02
        - check-dashboard-03
        - check-dashboard-04
        - check-dashboard-05
        - check-dashboard-06
        - check-dashboard-07
        - check-dashboard-08
        - check-dashboard-09
        - check-dashboard-10
        - check-dashboard-11
      attributes:
        horizon_config_group: apache
    cinder:
      required_controls:
        - check-block-01
        - check-block-02
    glance:
      required_controls: []
    nova:
      required_controls:
        - check-compute-01
        - check-compute-02
    keystone:
      required_controls:
        - check-identity-01
        - check-identity-02
    neutron:
      required_controls:
        - check-neutron-01
        - check-neutron-02

  rhel7:
    attributes:
      RHEL_07_030710_audit_key_name: audit_account_changes-V-38531
      client_alive_interval: '900'
      RHEL_07_030523_audit_key_name: actions-V-38578
    skip_controls: []
