---
- name: set os fact for rhel operating system
  set_fact:
    os: rhel
  when: ansible_distribution in ['CentOS', 'RedHat']

- name: set os fact for rhel operating system
  set_fact:
    os: ubuntu
  when: ansible_distribution in ['Ubuntu']

- name: make sure os is defined
  fail: msg="We don't support {{ ansible_distribution }} yet. OS should be CentOS, RedHat or Ubuntu."
  when: os is undefined

- name: set ssh_service fact for ubuntu
  set_fact:
    ssh_service: ssh
  when: os == 'ubuntu'

- name: set ssh_service fact for rhel
  set_fact:
    ssh_service: sshd
  when: os == 'rhel'

- name: set ca_bundle fact for ubuntu
  set_fact:
    ca_bundle: /etc/ssl/certs/ca-certificates.crt
  when: os == 'ubuntu'

- name: set ca_bundle fact for rhel
  set_fact:
    ca_bundle: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
  when: os == 'rhel'

- include: check_items.yml
  tags: ['precheck']
