---
# nova compute
- name: compute process check
  sensu_process_check: service=nova-compute
  notify: restart sensu-client

- name: neutron linuxbridge agent check
  sensu_process_check: service=neutron-linuxbridge-agent
  notify: restart sensu-client
  when: neutron.plugin=='ml2'

- name: nova cinder session check
  sensu_metrics_check: name=check-cinder-sessions plugin=check-cinder-sessions.py
                       interval=10
  notify: restart sensu-client
  when: not ceph.enabled|default('False')|bool
  
# remove neutron agents check on compute
- name: neutron agents check
  sensu_check_dict:
    name: "check-neutron-agents"
    check: "{{ sensu_checks.neutron.check_neutron_agents }}"
    state: "absent"
  notify: restart sensu-client missing ok

- name: neutron agents duplicate check
  sensu_check_dict:
    name: "check-neutron-agents-duplicate"
    check: "{{ sensu_checks.neutron.check_neutron_agents_duplicate }}"
    state: "absent"
  notify: restart sensu-client missing ok

- name: neutron router check multiple l3 agents active or all standby status
  sensu_check_dict:
    name: "check-neutron-l3-routers"
    check: "{{ sensu_checks.neutron.check_neutron_l3_routers }}"
    state: "absent"
  notify: restart sensu-client missing ok
  
- name: nova compute data out of sync check (only in Mitaka)
  sensu_check: name=check-nova-compute-not-sync plugin=check-log.rb use_sudo=true
               auto_resolve=false interval=120 occurrences=1
               args="-f '/var/log/nova/nova-compute.log' -q 'ERROR nova.compute.manager.*Error updating resources for node' --silent"
  notify: restart sensu-client
