---
- name: swift dispersion gate script
  template: src=check-swift-dispersion.sh mode=0755 owner=root group=root
            dest=/etc/sensu/plugins/check-swift-dispersion.sh

- name: swift dispersion check
  sensu_check: name=swift-dispersion plugin=check-swift-dispersion.sh
               interval=600 occurrences=1 use_sudo=true

- name: sensu account process checks
  sensu_process_check: service={{ item }} warn_over=30 crit_over=35
  with_items:
    - swift-account-auditor
    - swift-account-replicator
    - swift-account-reaper
    - swift-account-server

- name: sensu container process checks
  sensu_process_check: service={{ item }} warn_over=30 crit_over=35
  with_items:
    - swift-container-replicator
    - swift-container-updater
    - swift-container-auditor
    - swift-container-sync
    - swift-container-server

- name: sensu object process checks
  sensu_process_check: service={{ item }} warn_over=30 crit_over=35
  with_items:
    - swift-object-replicator
    - swift-object-updater
    - swift-object-server

- name: sensu proxy process checks
  sensu_process_check: service={{ item }}
  with_items:
    - swift-proxy
    - haproxy
    - memcached

- name: sensu check for mounted drives
  sensu_check: name=fstab-mounts plugin=check-fstab-mounts.rb
               args='-t xfs -z {{ swift.monitoring.sensu_checks.fstab_mounts.criticality }}'
               interval=60

- name: ucarp failover alert
  sensu_check: name=check-ucarp-failover plugin=check-log.rb use_sudo=true
               auto_resolve=false interval=20 occurrences=1
               args="-f {{ ( ursula_os == 'ubuntu' )| ternary('/var/log/syslog', '/var/log/messages') }} -q 'ucarp.+[Ss]witching to state' --silent"
  notify: restart sensu-client

- name: ucarp processes check
  sensu_check: name=check-ucarp-procs plugin=check-ucarp-procs.sh use_sudo=true
               args="-z {{ swift.monitoring.sensu_checks.check_ucarp_procs.criticality }}"
  notify: restart sensu-client

- name: swift sla metrics
  sensu_metrics_check: name=swift-sla-metrics plugin=metrics-os-api.py
                       args='-S swift --scheme {{ monitoring.graphite.cluster_prefix }}'
                       only_on_ip="{{ swift_undercloud_floating_ip | default( swift_floating_ip ) }}"
  notify: restart sensu-client

- name: swift usage metrics
  sensu_metrics_check:
    name: swift-usage-metrics
    plugin: metrics-swift.py
    args: "--ip-addr={{ primary_ip }} --scheme {{ monitoring.graphite.host_prefix }}"

