---
- name: refresh cert auths
  command: update-ca-certificates
  when: ansible_distribution == 'Ubuntu'

- name: restart logstash-forwarder
  service: name=logstash-forwarder state=restarted

- name: stop logstash-forwarder
  service: name=logstash-forwarder state=stopped

- name: start logstash-forwarder
  service: name=logstash-forwarder state=started

- name: restart rsyslog
  service: name=rsyslog state=restarted
