---
dependencies:
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: sensu-check
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: mysql
    logdata: "{{ percona.logs }}"
  - role: collectd-plugin
    when: collectd is defined and collectd.enabled|bool
