name: Ursula
title: Compliance Audit
maintainer: Ursula Team
copyright: IBM
copyright_email:
license: Apache 2.0
summary: An InSpec Compliance Profile
version: 0.1.0
depends:
{% for profile in inspec.profile_dependencies %}
- name: {{ profile.name }}
  path: '{{ inspec.dependency_path }}/current/{{ profile.name }}'
{% endfor %}
