---
stack_env: examp

state_path_base: /opt/stack/data

validate_certs: no

neutron:
  enable_external_interface: True
  lbaas:
    enabled: True

keystone:
  ldap_domain:
    enabled: True
    domain: users

serverspec:
  enabled: True
