---
- name: install firewalld
  package: name=firewalld
  register: result
  until: result|succeeded
  retries: 5

- name: Enable firewalld
  service: name=firewalld state=started enabled=yes

#- name: permit ucarp (IP protocol 112)
#  lineinfile: dest=/etc/ufw/before.rules
#              regexp="^-A ufw-before-input -p 112 -j ACCEPT"
#              line="-A ufw-before-input -p 112 -j ACCEPT"
#              insertafter="^-A ufw-before-input -p udp --sport 67 --dport 68 -j ACCEPT"

- name: Permit SSH
  firewalld: state=enabled permanent=true service=ssh source={{ item }}
  with_items: "{{ common.ssh.allow_from }}"

- name: Permit unrestricted access from remainder of cluster
  firewalld: state=enabled zone=trusted source={{ item.cidr }}
  with_items: "{{ undercloud_cidr }}"
  when: undercloud_cidr is defined

#- name: Do not enforce forwarding rules with UFW
#  lineinfile: dest=/etc/default/ufw regexp="^DEFAULT_FORWARD_POLICY"
#              line="DEFAULT_FORWARD_POLICY=\"ACCEPT\""

#- name: change UFW's sysctl.conf directory
#  lineinfile: dest=/etc/default/ufw regexp="^IPT_SYSCTL"
#              line="IPT_SYSCTL=/etc/sysctl.conf"
