---
- block:
  - name: custom CA cert directory
    file: dest=/usr/local/share/ca-certificates state=directory

  - name: (possibly self-signed) ssl cert
    template: src=openstack.cacrt
              dest=/usr/local/share/ca-certificates/{{ endpoints.main }}.crt
    notify: refresh CAs

  - name: Install any additional CA certificates
    copy:
      content: "{{ item.content | default(omit) }}"
      dest: "/usr/local/share/ca-certificates/{{ item.name }}.crt"
      src: "{{ item.src | default(omit) }}"
    with_items: "{{ ssl.extracacerts | default([]) }}"
    notify: refresh CAs
  when: os == 'ubuntu'

- block:
  - name: custom CA cert directory
    file: dest=/etc/pki/ca-trust/source/anchors state=directory

  - name: (possibly self-signed) ssl ca cert
    template: src=openstack.cacrt
              dest=/etc/pki/ca-trust/source/anchors/{{ endpoints.main }}.pem
    notify: refresh rhel CAs
    when: ssl.cacrt|default(None)

  - name: Install any additional CA certificates
    copy:
      content: "{{ item.content | default(omit) }}"
      dest: "/etc/pki/ca-trust/source/anchors/{{ item.name }}.pem"
      src: "{{ item.src | default(omit) }}"
    with_items: "{{ ssl.extracacerts | default([]) }}"
    notify: refresh rhel CAs
  when: os == 'rhel'


- name: ssl directory
  file: dest=/opt/stack/ssl state=directory

- name: install openstack SSL cert
  template:
    src: openstack.crt
    dest: /opt/stack/ssl/openstack.crt
    mode: 0644
  tags:
    - cert

# ugly hack: some python http libs don't honor the system ca-certs, and ship with
# their own list, instead.
# pre-install these client libs, and force them to use the system cert list.

- name: force our ssl cert for python libs on trusty
  file: src=/etc/ssl/certs/ca-certificates.crt dest={{ item }} owner=root
        mode=0644 state=link force=yes
  with_items:
    - "{{ basevenv_lib_dir }}/requests/cacert.pem"
  when: os == 'ubuntu'

- name: force our ssl cert for python libs on rhel
  file: src=/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt dest={{ item }} owner=root
        mode=0644 state=link force=yes
  with_items:
    - "{{ basevenv_lib_dir }}/requests/cacert.pem"
    - /usr/lib/python2.7/site-packages/requests/cacert.pem
    - "{{ ca_bundle }}"
  when: os == 'rhel'

- meta: flush_handlers

- name: update ca certificates
  command: update-ca-certificates
  when: os == 'ubuntu'

- name: update ca certificates (rhel)
  command: update-ca-trust
  when: os == 'rhel'
