---
project_name: heat
heat:
  services:
    heat_api: "{{ openstack_meta.heat.services.heat_api[os] }}"
    heat_api_cfn: "{{ openstack_meta.heat.services.heat_api_cfn[os] }}"
    heat_engine: "{{ openstack_meta.heat.services.heat_engine[os] }}"
  enabled: True
  heartbeat_timeout_threshold: 30
  distro:
    project_packages:
      - openstack-heat-api
      - openstack-heat-api-cfn
      - openstack-heat-engine
  source:
    rev: 'stable/newton'
    constrain: True
    upper_constraints: 'https://raw.githubusercontent.com/openstack/requirements/stable/newton/upper-constraints.txt'
    python_dependencies:
      - { name: PyMySQL }
    system_dependencies:
      ubuntu: []
      rhel: []
  alternatives:
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - heat-db-setup
    - heat-engine
    - heat-manage
  logs:
    - paths:
        - /var/log/heat/heat-api.log
      fields:
        type: openstack
        tags: heat,heat-api
    - paths:
        - /var/log/heat/heat-engine.log
      fields:
        type: openstack
        tags: heat,heat-engine
    - paths:
        - /var/log/heat/heat-manage.log
      fields:
        type: openstack
        tags: heat,heat-manage
  logging:
    debug: False
    verbose: True
  cafile: "{{ ssl.cafile|default('/etc/ssl/certs/ca-certificates.crt') }}"
  plugin_dirs: []
  engine_workers: 4
  api_workers: 5
  monitoring:
    sensu_checks:
      check_heat_api:
        criticality: 'critical'
  auditing:
    enabled: False
    logging: False
